version: '3'
services:
  php:
    build: ./php
    ports:
      - '80:80'
    working_dir: /root/php
    volumes:
      - ./php/src:/var/www/html:cached # <--- This will map ./php to /root/php inside the container.